apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloblio-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: bloblio.local
    http:
      paths:
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: auth-server
            port:
              number: 3000
      - path: /get-server
        pathType: Prefix
        backend:
          service:
            name: loadbalancer
            port:
              number: 3002
      - path: /ffa.*
        pathType: Prefix
        backend:
          service:
            name: game-server
            port:
              number: 8080
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: client
            port:
              number: 80
